chore(upgrade_arrow): upgrade to apache arrow 7
influxdata/influxdb-iox-client-go pull request #14
Opened 2022-03-04 10:17 UTC by skartikey

2022-03-04 15:04 UTC, wolffcm reviewed
This all seems reasonable, what's up with the change in `run-lint.sh`?

Obviously someone on the IOx team should review before you merge. Can you add a description to the PR and link to the relevant issue?

2022-03-04 15:04 UTC, wolffcm commented on run-lint.sh
> +exit "$HAS_FMT_ERR"
What's this change about?

2022-03-04 15:26 UTC, jacobmarble requested changes
Please rebase on HEAD of main and remove `vendor/` from this PR. Could do that with .gitignore if you like.

I need to review the rest afterward, but the above will simplify.

2022-03-04 16:01 UTC, skartikey commented on run-lint.sh
> +exit "$HAS_FMT_ERR"
I was getting a linter error in the CI for vendor directories. So wrote it to ignore the vendor directory. 
But it's not required anymore as I am going to put vendor/ directory in the `.gitignore` file.

2022-03-04 16:15 UTC, skartikey commented
> Please rebase on HEAD of main and remove `vendor/` from this PR. Could do that with .gitignore if you like.
> 
> I need to review the rest afterward, but the above will simplify.

@jacobmarble Thanks for the suggestion. I did the changes.

2022-03-05 00:39 UTC, jacobmarble approved these changes

2022-03-05 00:44 UTC, merged

2022-03-10 22:58 UTC, jacobmarble commented
This change broke the `ioxsql` tests. This package's tests depend on a running instance of IOx, so it's hard to catch failures like this. I'll see if a newer version of arrow fixes the issue.

```
--- FAIL: TestNormalLifeCycle (0.03s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10279603c]
...
github.com/influxdata/influxdb-iox-client-go/ioxsql.(*rows).Next(0x14000110180, {0x1400012c240, 0x2, 0x2})
        /Users/jacobmarble/projects/influxdb-iox-client-go/ioxsql/driver_rows.go:73 +0x70
...
github.com/influxdata/influxdb-iox-client-go/ioxsql_test.TestNormalLifeCycle(0x140002fe820)
        /Users/jacobmarble/projects/influxdb-iox-client-go/ioxsql/driver_test.go:106 +0x22c
...
FAIL    github.com/influxdata/influxdb-iox-client-go/ioxsql     0.262s
FAIL
```

2022-03-10 23:02 UTC, jacobmarble commented
It seems that this is still a problem in arrow/HEAD.